import {
  METHODOLOGY_VERSION,
  SCORING_ZONE_YARDS,
  type CompletedRound,
  type CompletedScoringHole,
} from "@/domain/scoring";

/**
 * A fixed, realistic 18-hole round used as the cross-environment parity fixture.
 * `analyseRound(canonicalRound)` must deep-equal `canonicalRound.analysis.json`.
 * When the server-side engine path exists it runs this same fixture and must
 * produce byte-identical output (plan: "golden-file parity test").
 *
 * Do not edit casually — a change here is a deliberate methodology change and
 * must bump METHODOLOGY_VERSION and regenerate the golden file.
 */
const h = (hole: CompletedScoringHole): CompletedScoringHole => hole;

const holes: CompletedScoringHole[] = [
  h({
    status: "completed",
    holeNumber: 1,
    par: 4,
    pickedUp: false,
    score: 4,
    shotsToZone: 2,
    putts: 2,
    firstPuttDistance: "15-30ft",
    penaltyStrokes: 0,
    bunkerShots: 0,
    bunkersVisited: 0,
    teeOutcome: "clear",
    teeLie: "fairway",
    approachAttempts: [
      { sequence: 1, distanceBand: "150-174", result: "green" },
    ],
    mistakes: [],
  }),
  h({
    status: "completed",
    holeNumber: 2,
    par: 3,
    pickedUp: false,
    score: 3,
    shotsToZone: 1,
    putts: 2,
    firstPuttDistance: "15-30ft",
    penaltyStrokes: 0,
    bunkerShots: 0,
    bunkersVisited: 0,
    teeOutcome: "clear",
    teeLie: "fairway",
    approachAttempts: [],
    mistakes: [],
  }),
  h({
    status: "completed",
    holeNumber: 3,
    par: 5,
    pickedUp: false,
    score: 6,
    shotsToZone: 3,
    putts: 2,
    firstPuttDistance: "5-15ft",
    penaltyStrokes: 0,
    bunkerShots: 0,
    bunkersVisited: 0,
    teeOutcome: "compromised",
    teeLie: "rough",
    approachAttempts: [
      { sequence: 1, distanceBand: "200-plus", result: "scoring-zone" },
    ],
    mistakes: [],
  }),
  h({
    status: "completed",
    holeNumber: 4,
    par: 4,
    pickedUp: false,
    score: 6,
    shotsToZone: 3,
    putts: 2,
    firstPuttDistance: "15-30ft",
    penaltyStrokes: 1,
    bunkerShots: 0,
    bunkersVisited: 0,
    teeOutcome: "penalty",
    teeLie: "trees-other",
    approachAttempts: [
      {
        sequence: 1,
        distanceBand: "125-149",
        result: "missed-zone",
        missDirection: "right",
      },
    ],
    mistakes: ["tee"],
  }),
  h({
    status: "completed",
    holeNumber: 5,
    par: 4,
    pickedUp: false,
    score: 4,
    shotsToZone: 2,
    putts: 2,
    firstPuttDistance: "under-5ft",
    penaltyStrokes: 0,
    bunkerShots: 0,
    bunkersVisited: 0,
    teeOutcome: "clear",
    teeLie: "fairway",
    approachAttempts: [
      { sequence: 1, distanceBand: "100-124", result: "green" },
    ],
    mistakes: [],
  }),
  h({
    status: "completed",
    holeNumber: 6,
    par: 3,
    pickedUp: false,
    score: 5,
    shotsToZone: 1,
    putts: 3,
    firstPuttDistance: "30-50ft",
    penaltyStrokes: 0,
    bunkerShots: 1,
    bunkersVisited: 1,
    teeOutcome: "compromised",
    teeLie: "bunker",
    approachAttempts: [],
    mistakes: ["putting"],
  }),
  h({
    status: "completed",
    holeNumber: 7,
    par: 4,
    pickedUp: false,
    score: 5,
    shotsToZone: 3,
    putts: 2,
    firstPuttDistance: "5-15ft",
    penaltyStrokes: 0,
    bunkerShots: 0,
    bunkersVisited: 0,
    teeOutcome: "recovery-required",
    teeLie: "trees-other",
    approachAttempts: [
      { sequence: 1, distanceBand: "175-199", result: "scoring-zone" },
    ],
    mistakes: ["tee"],
  }),
  h({
    status: "completed",
    holeNumber: 8,
    par: 5,
    pickedUp: false,
    score: 5,
    shotsToZone: 3,
    putts: 2,
    firstPuttDistance: "5-15ft",
    penaltyStrokes: 0,
    bunkerShots: 0,
    bunkersVisited: 0,
    teeOutcome: "clear",
    teeLie: "fairway",
    approachAttempts: [
      { sequence: 1, distanceBand: "under-100", result: "green" },
    ],
    mistakes: [],
  }),
  h({
    status: "completed",
    holeNumber: 9,
    par: 4,
    pickedUp: false,
    score: 4,
    shotsToZone: 2,
    putts: 2,
    firstPuttDistance: "15-30ft",
    penaltyStrokes: 0,
    bunkerShots: 0,
    bunkersVisited: 0,
    teeOutcome: "clear",
    teeLie: "rough",
    approachAttempts: [
      { sequence: 1, distanceBand: "150-174", result: "green" },
    ],
    mistakes: [],
  }),
  h({
    status: "completed",
    holeNumber: 10,
    par: 4,
    pickedUp: false,
    score: 5,
    shotsToZone: 2,
    putts: 3,
    firstPuttDistance: "30-50ft",
    penaltyStrokes: 0,
    bunkerShots: 0,
    bunkersVisited: 0,
    teeOutcome: "clear",
    teeLie: "fairway",
    approachAttempts: [
      { sequence: 1, distanceBand: "150-174", result: "green" },
    ],
    mistakes: ["putting"],
  }),
  h({
    status: "completed",
    holeNumber: 11,
    par: 3,
    pickedUp: false,
    score: 3,
    shotsToZone: 1,
    putts: 2,
    firstPuttDistance: "5-15ft",
    penaltyStrokes: 0,
    bunkerShots: 0,
    bunkersVisited: 0,
    teeOutcome: "clear",
    teeLie: "fairway",
    approachAttempts: [],
    mistakes: [],
  }),
  h({
    status: "completed",
    holeNumber: 12,
    par: 5,
    pickedUp: false,
    score: 7,
    shotsToZone: 4,
    putts: 2,
    firstPuttDistance: "15-30ft",
    penaltyStrokes: 1,
    bunkerShots: 0,
    bunkersVisited: 0,
    teeOutcome: "clear",
    teeLie: "fairway",
    approachAttempts: [
      { sequence: 1, distanceBand: "200-plus", result: "intentional-layup" },
      {
        sequence: 2,
        distanceBand: "125-149",
        result: "missed-zone",
        missDirection: "short",
      },
    ],
    mistakes: ["strategy"],
  }),
  h({
    status: "completed",
    holeNumber: 13,
    par: 4,
    pickedUp: false,
    score: 4,
    shotsToZone: 2,
    putts: 2,
    firstPuttDistance: "15-30ft",
    penaltyStrokes: 0,
    bunkerShots: 0,
    bunkersVisited: 0,
    teeOutcome: "clear",
    teeLie: "fairway",
    approachAttempts: [
      { sequence: 1, distanceBand: "125-149", result: "green" },
    ],
    mistakes: [],
  }),
  h({
    status: "completed",
    holeNumber: 14,
    par: 4,
    pickedUp: false,
    score: 8,
    shotsToZone: 3,
    putts: 3,
    firstPuttDistance: "15-30ft",
    penaltyStrokes: 0,
    bunkerShots: 3,
    bunkersVisited: 1,
    teeOutcome: "compromised",
    teeLie: "rough",
    approachAttempts: [
      {
        sequence: 1,
        distanceBand: "150-174",
        result: "missed-zone",
        missDirection: "long",
      },
    ],
    mistakes: ["short-game", "short-game"],
  }),
  h({
    status: "completed",
    holeNumber: 15,
    par: 3,
    pickedUp: false,
    score: 3,
    shotsToZone: 1,
    putts: 2,
    firstPuttDistance: "5-15ft",
    penaltyStrokes: 0,
    bunkerShots: 0,
    bunkersVisited: 0,
    teeOutcome: "clear",
    teeLie: "fairway",
    approachAttempts: [],
    mistakes: [],
  }),
  h({
    status: "completed",
    holeNumber: 16,
    par: 5,
    pickedUp: false,
    score: 6,
    shotsToZone: 3,
    putts: 2,
    firstPuttDistance: "15-30ft",
    penaltyStrokes: 0,
    bunkerShots: 0,
    bunkersVisited: 0,
    teeOutcome: "clear",
    teeLie: "fairway",
    approachAttempts: [
      { sequence: 1, distanceBand: "100-124", result: "scoring-zone" },
    ],
    mistakes: [],
  }),
  h({
    status: "completed",
    holeNumber: 17,
    par: 4,
    pickedUp: false,
    score: 5,
    shotsToZone: 2,
    putts: 3,
    firstPuttDistance: "30-50ft",
    penaltyStrokes: 0,
    bunkerShots: 0,
    bunkersVisited: 0,
    teeOutcome: "clear",
    teeLie: "fairway",
    approachAttempts: [
      { sequence: 1, distanceBand: "150-174", result: "green" },
    ],
    mistakes: ["putting"],
  }),
  h({
    status: "completed",
    holeNumber: 18,
    par: 4,
    pickedUp: false,
    score: 4,
    shotsToZone: 2,
    putts: 2,
    firstPuttDistance: "5-15ft",
    penaltyStrokes: 0,
    bunkerShots: 0,
    bunkersVisited: 0,
    teeOutcome: "clear",
    teeLie: "fairway",
    approachAttempts: [
      { sequence: 1, distanceBand: "175-199", result: "green" },
    ],
    mistakes: [],
  }),
];

export const canonicalRound: CompletedRound = {
  id: "canonical-round",
  scoringZoneYards: SCORING_ZONE_YARDS,
  handicapAtStart: 14,
  plannedHoleCount: 18,
  holes,
  methodologyVersion: METHODOLOGY_VERSION,
};
